### ISSUE TITLE
Error: Unable to construct concave hull

### ISSUE THREAD

**Issue by henry2004y** [lstagner/ConcaveHull.jl#9]
Hi,

I have encountered the error message `Unable to construct concave hull`, but I don't understand the reason. Here is the script:
```
using DelimitedFiles, ConcaveHull

points = readdlm("points.txt", ',', header=true)[1]

v = [[points[i,1], points[i,2]] for i in 1:size(points,1)]

hull = concave_hull(v)

#using PyPlot
#scatter(points[:,1],points[:,2])
```

When I tried with some random points in a ring which looks similar to the attached data using the following script
```
using PyPlot, ConcaveHull
function ringpoints(lo::Integer, hi::Integer, ndots::Integer)
   canvas = zeros(2,ndots)
   i = 0
   while i < ndots
      r = rand()*(hi-lo) + lo
      θ = rand()*2π
      x = r*cos(θ)
      y = r*sin(θ)
      canvas[:,i+1] = [x, y]
      i += 1
   end
   return canvas
end

points = ringpoints(3,6,2000)
scatter(points[1,:], points[2,:])
v = [[points[1,i], points[2,i]] for i = 1:size(points,2)]
hull = concave_hull(v)
```
it just works fine.

So what is the problem with my data? Is there any constraint?

Thanks!

[points.txt](https://github.com/lstagner/ConcaveHull.jl/files/3843888/points.txt)

**Comment by lstagner** [comment]
You are probably running in same problem as Issue #3

**Comment by henry2004y** [comment]
Yes you are right. I would suggest a slightly modified error message for this issue, to make it more clear.

Thanks for your quick response! I really appreciate it!

**Comment by lstagner** [comment]
The issue is that there are more than 3 points that are co-linear with the edges of the concave hull. I have fixed the issue on master and it works with your data although you may want to use smooth out the hull by increasing the number of neighbors used.
